// ============================================================
//  BrandPlayzone — Game Data Layer
//  India · Personal Care · v1.0
// ============================================================
window.BPZ = window.BPZ || {};

BPZ.data = {

  // ── MARKET CONTEXT ──────────────────────────────────────
  market: {
    country: 'India',
    category: 'Personal Care',
    totalMarketCrore: 150000,   // ₹1.5 Lakh Crore total PC market
    categoryGrowthPct: 9,
    urbanRuralSplit: '55 / 45',
    topRetailers: ['Reliance Retail', 'DMart', 'Amazon', 'Flipkart', 'Nykaa'],
    context: 'India\'s Personal Care market is the 4th largest in Asia, driven by premiumisation, the naturals surge, and rapid e-commerce adoption. Kirana stores still account for ~50% of sales.',
  },

  // ── SUB-CATEGORIES ──────────────────────────────────────
  subCategories: [
    {
      id: 'hair-care',
      name: 'Hair Care',
      icon: '💆',
      marketSizeCrore: 22000,
      growth: '9% CAGR',
      description: 'Shampoos, conditioners, oils, serums. High premiumisation, naturals disruption.',
      keyInsight: 'Category is being reshaped by naturals-first D2C brands. Kirana still rules volume; Nykaa drives value.',
      competitors: [
        { id: 'lumora',      name: 'Lumora',      archetype: 'Market Leader',    share: 31, positioning: 'mass', equity: 74 },
        { id: 'pristine',    name: 'Pristine',    archetype: 'Premium Challenger', share: 19, positioning: 'premium', equity: 68 },
        { id: 'naturecraft', name: 'NatureCraft', archetype: 'D2C Disruptor',    share: 9,  positioning: 'premium', equity: 61 },
        { id: 'massglow',    name: 'MassGlow',    archetype: 'Value Fighter',    share: 14, positioning: 'value',  equity: 42 },
      ],
    },
    {
      id: 'skin-care',
      name: 'Skin Care',
      icon: '✨',
      marketSizeCrore: 18000,
      growth: '13% CAGR',
      description: 'Moisturisers, face wash, sunscreen, serums. India\'s fastest-growing PC segment.',
      keyInsight: 'Gen Z is driving ingredient-led purchasing. K-Beauty influence is high. Sunscreen is the breakout sub-segment.',
      competitors: [
        { id: 'lumora',      name: 'Lumora',      archetype: 'Market Leader',    share: 27, positioning: 'masstige', equity: 71 },
        { id: 'pristine',    name: 'Pristine',    archetype: 'Premium Challenger', share: 21, positioning: 'premium', equity: 73 },
        { id: 'naturecraft', name: 'NatureCraft', archetype: 'D2C Disruptor',    share: 12, positioning: 'premium', equity: 66 },
        { id: 'massglow',    name: 'MassGlow',    archetype: 'Value Fighter',    share: 11, positioning: 'value',  equity: 38 },
      ],
    },
    {
      id: 'body-care',
      name: 'Body Care',
      icon: '🧴',
      marketSizeCrore: 14000,
      growth: '7% CAGR',
      description: 'Body wash, soaps, lotions, hand creams. High penetration, growing premiumisation.',
      keyInsight: 'Soap-to-bodywash trade-up is the big opportunity. Rural volumes are huge but margin is thin.',
      competitors: [
        { id: 'lumora',      name: 'Lumora',      archetype: 'Market Leader',    share: 36, positioning: 'mass', equity: 76 },
        { id: 'pristine',    name: 'Pristine',    archetype: 'Premium Challenger', share: 17, positioning: 'premium', equity: 65 },
        { id: 'naturecraft', name: 'NatureCraft', archetype: 'D2C Disruptor',    share: 7,  positioning: 'masstige', equity: 58 },
        { id: 'massglow',    name: 'MassGlow',    archetype: 'Value Fighter',    share: 18, positioning: 'value',  equity: 44 },
      ],
    },
  ],

  // ── CONSUMER SEGMENTS ───────────────────────────────────
  segments: [
    {
      id: 'metro-premium',
      name: 'Metro Premium Millennial',
      icon: '🏙️',
      age: '25–35',
      income: '₹1.5L+ / month household',
      location: 'Mumbai, Delhi, Bangalore, Hyderabad',
      size: '18M consumers',
      description: 'Career-driven, aspirational, globally aware. Buys brands that signal status and align with values.',
      values: ['Premium quality', 'Natural/clean ingredients', 'Brand reputation', 'Convenience'],
      switchTrigger: 'New innovation launch, viral influencer review',
      mediaAffinity: { tv: 0.4, digital: 1.5 },
      channelPreference: ['e-commerce', 'quick-commerce', 'modern-trade'],
      preferredPositioning: 'premium',
      purchaseFreq: '5–6 weeks',
      basket: '₹600–₹1,200/trip',
      colour: '#6366f1',
    },
    {
      id: 'aspiring-middle',
      name: 'Aspiring Middle Class',
      icon: '🏘️',
      age: '22–40',
      income: '₹40K–₹80K / month household',
      location: 'Tier 1 & 2 cities',
      size: '85M consumers',
      description: 'Value-conscious but aspirational. Wants brands the "metros" use at a fair price. Heavy TV consumer.',
      values: ['Value for money', 'Trust & reliability', 'Aspirational branding', 'Peer recommendations'],
      switchTrigger: 'Price promotion, strong TVC campaign',
      mediaAffinity: { tv: 1.3, digital: 1.0 },
      channelPreference: ['modern-trade', 'e-commerce', 'general-trade'],
      preferredPositioning: 'masstige',
      purchaseFreq: '4–6 weeks',
      basket: '₹250–₹600/trip',
      colour: '#22d3ee',
    },
    {
      id: 'value-hunter',
      name: 'Value Hunter',
      icon: '🛒',
      age: '25–50',
      income: '<₹25K / month household',
      location: 'Tier 2–4 cities and rural',
      size: '180M consumers',
      description: 'Price above all. Kirana loyalists. Sachet economy is their primary format. TV is dominant media.',
      values: ['Lowest price', 'Large pack value', 'Known/trusted brand', 'Retailer recommendation'],
      switchTrigger: 'Even ₹5–₹10 price difference',
      mediaAffinity: { tv: 1.5, digital: 0.4 },
      channelPreference: ['general-trade', 'modern-trade'],
      preferredPositioning: 'value',
      purchaseFreq: 'Weekly (sachets) / Monthly (mid packs)',
      basket: '₹80–₹200/trip',
      colour: '#f59e0b',
    },
    {
      id: 'gen-z-health',
      name: 'Health-Conscious Gen Z',
      icon: '🌿',
      age: '18–26',
      income: 'Individual ₹20K–₹50K / month',
      location: 'Metro and Tier 1 cities',
      size: '42M consumers',
      description: 'Ingredient-obsessed, sustainability-aware, easily influenced by Reels & Reddit. Hates greenwashing.',
      values: ['Clean ingredient lists', 'Sustainability', 'Science-backed claims', 'Community trust'],
      switchTrigger: 'Viral TikTok/Reels moment, brand controversy',
      mediaAffinity: { tv: 0.2, digital: 1.8 },
      channelPreference: ['e-commerce', 'quick-commerce', 'd2c'],
      preferredPositioning: 'premium',
      purchaseFreq: '6–8 weeks',
      basket: '₹400–₹900/trip',
      colour: '#10b981',
    },
    {
      id: 'traditional-loyalist',
      name: 'Traditional Loyalist',
      icon: '🏠',
      age: '35–55',
      income: '₹30K–₹70K / month household',
      location: 'Tier 1–3 cities',
      size: '95M consumers',
      description: 'Brand-loyal for years. Trusts doctor/chemist recommendations. Hard to switch; once won, very sticky.',
      values: ['Trusted heritage brands', 'Dermatologist/doctor endorsed', 'Family tradition', 'Proven efficacy'],
      switchTrigger: 'Doctor recommendation, major brand crisis',
      mediaAffinity: { tv: 1.6, digital: 0.5 },
      channelPreference: ['general-trade', 'pharmacy', 'modern-trade'],
      preferredPositioning: 'mass',
      purchaseFreq: 'Monthly',
      basket: '₹200–₹500/trip',
      colour: '#f43f5e',
    },
  ],

  // ── CHANNELS ────────────────────────────────────────────
  channels: [
    {
      id: 'modern-trade',
      name: 'Modern Trade',
      icon: '🏬',
      examples: 'DMart, Reliance Retail, Big Bazaar, Spencer\'s',
      revenueSplit: 18,   // % of category revenue
      entryBudgetCrore: 2,
      maxDistPct: 72,
      timeToROI: '4–6 months',
      tradeTerm: '25% margin, 60-day credit',
      revenueWeight: 0.18,
      pros: ['High visibility', 'Planogram placement', 'Premium shopper access'],
      cons: ['High listing fees', 'Slow distribution ramp', 'Dominated by leaders'],
      bestFor: ['metro-premium', 'aspiring-middle'],
    },
    {
      id: 'general-trade',
      name: 'General Trade / Kirana',
      icon: '🏪',
      examples: '14M+ mom-and-pop stores across India',
      revenueSplit: 52,
      entryBudgetCrore: 4,
      maxDistPct: 88,
      timeToROI: '6–9 months',
      tradeTerm: '15% margin, 30-day credit',
      revenueWeight: 0.52,
      pros: ['Largest reach', 'Trust factor in small towns', 'No listing fee'],
      cons: ['Requires large distributor/RSM network', 'Hard to audit'],
      bestFor: ['value-hunter', 'traditional-loyalist', 'aspiring-middle'],
    },
    {
      id: 'e-commerce',
      name: 'E-Commerce',
      icon: '📦',
      examples: 'Amazon, Flipkart, Nykaa, Meesho',
      revenueSplit: 17,
      entryBudgetCrore: 0.5,
      maxDistPct: 96,
      timeToROI: '1–3 months',
      tradeTerm: '30–35% commission',
      revenueWeight: 0.17,
      pros: ['Instant all-India reach', 'Data-rich', 'Low entry cost'],
      cons: ['Price visibility & wars', 'Thin margins', 'Returns'],
      bestFor: ['metro-premium', 'aspiring-middle', 'gen-z-health'],
    },
    {
      id: 'quick-commerce',
      name: 'Quick Commerce',
      icon: '⚡',
      examples: 'Blinkit, Zepto, Swiggy Instamart',
      revenueSplit: 5,
      entryBudgetCrore: 0.3,
      maxDistPct: 60,  // metro-only for now
      timeToROI: '1–2 months',
      tradeTerm: '40% commission',
      revenueWeight: 0.05,
      pros: ['Fastest-growing channel', 'Urban premium shoppers', 'High impulse'],
      cons: ['Only Tier 1 cities', 'Highest commission', 'Packaging limitations'],
      bestFor: ['metro-premium', 'gen-z-health'],
    },
    {
      id: 'pharmacy',
      name: 'Pharmacy / Chemist',
      icon: '💊',
      examples: 'Apollo Pharmacy, Medplus, local chemists',
      revenueSplit: 6,
      entryBudgetCrore: 0.8,
      maxDistPct: 55,
      timeToROI: '3–5 months',
      tradeTerm: '20% margin',
      revenueWeight: 0.06,
      pros: ['Credibility boost (derma/health positioning)', 'Less cluttered shelf'],
      cons: ['Limited to health-claims SKUs', 'Smaller footprint'],
      bestFor: ['traditional-loyalist', 'metro-premium'],
    },
    {
      id: 'd2c',
      name: 'D2C (Own website/app)',
      icon: '🌐',
      examples: 'Your own brand.com + WhatsApp ordering',
      revenueSplit: 2,
      entryBudgetCrore: 0.5,
      maxDistPct: 99,
      timeToROI: '3–6 months',
      tradeTerm: 'Full margin (0%)',
      revenueWeight: 0.02,
      pros: ['100% margin', 'First-party data', 'Community building'],
      cons: ['Requires high digital marketing spend', 'Small volume at start'],
      bestFor: ['gen-z-health', 'metro-premium'],
    },
  ],

  // ── BUDGET TIERS ────────────────────────────────────────
  budgetTiers: [
    {
      id: 'bootstrapped',
      name: 'Bootstrapped',
      budgetCrore: 3,
      icon: '🌱',
      description: '₹3 Crore / year. Founder-led. Every rupee counts.',
      companyArchetypes: ['startup'],
    },
    {
      id: 'funded',
      name: 'Funded Start-up',
      budgetCrore: 15,
      icon: '🚀',
      description: '₹15 Crore / year. Series A/B funded. Growth mode.',
      companyArchetypes: ['startup', 'local-challenger'],
    },
    {
      id: 'capitalized',
      name: 'Well-Capitalised',
      budgetCrore: 60,
      icon: '💼',
      description: '₹60 Crore / year. Established challenger or regional giant.',
      companyArchetypes: ['local-challenger'],
    },
    {
      id: 'mnc',
      name: 'MNC Scale',
      budgetCrore: 250,
      icon: '🌏',
      description: '₹250 Crore / year. Full MNC war chest. Market ambition.',
      companyArchetypes: ['mnc'],
    },
  ],

  // ── COMPANY ARCHETYPES ──────────────────────────────────
  companyArchetypes: [
    { id: 'startup',         name: 'Startup / D2C',      icon: '⚡', qualityMod: 0.78, description: 'Agile, purpose-led, high risk. Quality depends on formulation investment.' },
    { id: 'local-challenger',name: 'Local Challenger',   icon: '🦁', qualityMod: 0.87, description: 'Strong distribution roots, competitive pricing. Growing portfolio.' },
    { id: 'mnc',             name: 'MNC',                icon: '🌍', qualityMod: 0.96, description: 'Deep pockets, R&D scale, global best practices. Slower to move.' },
  ],

  // ── SKU TEMPLATES ───────────────────────────────────────
  skuTemplates: {
    'hair-care': [
      { id: 'shampoo-premium', name: 'Premium Shampoo 200ml', positioning: 'premium',  asp: 349, gmPct: 65, description: 'Salon-grade formula, premium fragrance, glass bottle.' },
      { id: 'shampoo-daily',   name: 'Daily Shampoo 200ml',   positioning: 'masstige', asp: 199, gmPct: 58, description: 'Everyday nourishment, light fragrance, recyclable pack.' },
      { id: 'shampoo-mass',    name: 'Volume Shampoo 400ml',  positioning: 'mass',     asp: 150, gmPct: 48, description: 'Value pack, mild formula, great lather.' },
      { id: 'shampoo-sachet',  name: 'Shampoo Sachet 8ml',    positioning: 'value',    asp: 5,   gmPct: 36, description: 'Rural and trial-driven. High volume, thin margin.' },
      { id: 'conditioner',     name: 'Conditioner 200ml',     positioning: 'masstige', asp: 249, gmPct: 60, description: 'Smoothing, reduce breakage. Premium add-on SKU.' },
      { id: 'hair-serum',      name: 'Hair Serum 50ml',       positioning: 'premium',  asp: 499, gmPct: 68, description: 'Hero product for naturals/Gen Z positioning.' },
      { id: 'hair-oil',        name: 'Hair Oil 200ml',        positioning: 'mass',     asp: 120, gmPct: 46, description: 'Strong rural heritage. High-volume, traditional segment.' },
    ],
    'skin-care': [
      { id: 'face-wash-prem', name: 'Face Wash 100ml',        positioning: 'premium',  asp: 399, gmPct: 68, description: 'Natural actives, dermatologist tested.' },
      { id: 'moisturiser',    name: 'Daily Moisturiser 100ml',positioning: 'masstige', asp: 299, gmPct: 62, description: 'SPF 15, lightweight, suits Indian climate.' },
      { id: 'sunscreen',      name: 'Sunscreen SPF 50 75ml',  positioning: 'premium',  asp: 549, gmPct: 70, description: 'Fastest-growing sub-segment. Gen Z favourite.' },
      { id: 'facewash-mass',  name: 'Face Wash 150ml',        positioning: 'mass',     asp: 149, gmPct: 49, description: 'Everyday use, family-friendly.' },
    ],
    'body-care': [
      { id: 'bodywash-prem',  name: 'Body Wash 300ml',        positioning: 'premium',  asp: 449, gmPct: 67, description: 'Luxury lather, long-lasting fragrance.' },
      { id: 'soap-mass',      name: 'Soap Bar 100g (4-pack)', positioning: 'mass',     asp: 110, gmPct: 44, description: 'Household staple. Kirana backbone.' },
      { id: 'lotion',         name: 'Body Lotion 300ml',      positioning: 'masstige', asp: 299, gmPct: 61, description: 'Rising with trade-up trend. Good margin.' },
    ],
  },

  // ── EVENT CARDS (Year 1–3 random draws) ─────────────────
  events: [
    {
      id: 'raw-material-spike',
      year: 1,
      category: 'Supply Chain',
      categoryColour: '#f59e0b',
      icon: '📈',
      title: 'Raw Material Cost Surge',
      description: 'Global commodity markets have sent key ingredients (palm oil, SLS, silicones) up 28% this quarter. Your Cost of Goods is about to take a hit.',
      impact: 'Your gross margin will drop 7–10% if you take no action.',
      options: [
        { id: 'absorb',      label: 'Absorb the hit',             cost: 0,   description: 'Protect consumer price. Margin takes the blow. Brand equity untouched.', metricEffect: { gmMod: -0.08, equityMod: 0 } },
        { id: 'price-hike',  label: 'Increase price by 8%',       cost: 0,   description: 'Protect margin. Risk 10–15% volume loss from price-sensitive segments.', metricEffect: { gmMod: 0.02, awareMod: -4, shareMod: -0.8 } },
        { id: 'reformulate', label: 'Reformulate to lower-cost base', cost: 0.5, description: 'Protect price & margin but risk product quality perception.', metricEffect: { gmMod: 0.03, equityMod: -5 } },
      ],
    },
    {
      id: 'competitor-price-war',
      year: 1,
      category: 'Competitive',
      categoryColour: '#f43f5e',
      icon: '⚔️',
      title: 'Lumora Drops Price 15%',
      description: 'Market leader Lumora has declared a price war, slashing their hero SKU price by 15% — clearly targeting your segment. Retailers are already stocking up.',
      impact: 'Estimated 1.2% market share loss over 6 months if you don\'t react.',
      options: [
        { id: 'match-price', label: 'Match the price cut',         cost: 0,   description: 'Protect volume. Margin pressure of ~6%. Seen as reactive.', metricEffect: { gmMod: -0.06, shareMod: 0.4 } },
        { id: 'promote',     label: 'Increase promotions (+₹1.5Cr BTL)', cost: 1.5, description: 'Fight visibility without dropping MRP. Shopper engagement boost.', metricEffect: { awareMod: 3, trialMod: 4, shareMod: 0.3 } },
        { id: 'hold-course', label: 'Hold course, double down on brand', cost: 0.5, description: 'Invest in brand-building, not price war. Better long-term but short-term share risk.', metricEffect: { equityMod: 6, shareMod: -0.5, awareMod: 2 } },
      ],
    },
    {
      id: 'influencer-viral',
      year: 1,
      category: 'Opportunity',
      categoryColour: '#10b981',
      icon: '🚀',
      title: 'Micro-Influencer Goes Viral',
      description: 'A beauty micro-influencer with 480K followers posted an honest review of your product — and it\'s blowing up. 12M views in 48 hours. Comments are mostly positive.',
      impact: 'Awareness can spike by 6–10% if you capitalise quickly.',
      options: [
        { id: 'partner',    label: 'Formally partner (₹0.5Cr)',   cost: 0.5, description: 'Lock in the influencer, create content series. Sustained lift.', metricEffect: { awareMod: 9, equityMod: 4 } },
        { id: 'ride-wave',  label: 'Ride the organic wave',       cost: 0,   description: 'Engage in comments, share the post. Free but short-lived.', metricEffect: { awareMod: 5, equityMod: 2 } },
        { id: 'ignore',     label: 'Don\'t engage — brand purity', cost: 0,   description: 'Maintain curated image. Miss the window but protect brand voice.', metricEffect: { awareMod: 1 } },
      ],
    },
    {
      id: 'qcom-surge',
      year: 1,
      category: 'Channel Shift',
      categoryColour: '#22d3ee',
      icon: '⚡',
      title: 'Quick Commerce Demand Surge',
      description: 'Blinkit and Zepto have seen 240% YoY growth in Personal Care in the last quarter. Urban consumers now want their shampoo in 10 minutes. Retailers are pushing for PC listings.',
      impact: 'Quick commerce is now 5% of urban PC sales and growing fast.',
      options: [
        { id: 'enter-qcom',  label: 'Enter quick commerce now (₹0.3Cr)', cost: 0.3, description: 'Early mover advantage. Premium segment penetration. Limited to metros.', metricEffect: { distMod: 4, shareMod: 0.3, awareMod: 2 } },
        { id: 'wait-watch',  label: 'Wait and evaluate',                  cost: 0,   description: 'Monitor without investing. No upside but no risk.', metricEffect: {} },
      ],
    },
    {
      id: 'regulator-flag',
      year: 2,
      category: 'Regulatory',
      categoryColour: '#f59e0b',
      icon: '⚠️',
      title: 'ASCI Flags Your Product Claim',
      description: 'The Advertising Standards Council of India has issued a notice questioning your "clinically proven" claim on packaging. A competitor filed the complaint. Resolution needed in 30 days.',
      impact: 'Retailer confidence dip. Media coverage could hurt brand perception.',
      options: [
        { id: 'modify-claim', label: 'Proactively modify claims',      cost: 0.2, description: 'Quickly rephrase. Minor brand impact but show proactiveness.', metricEffect: { equityMod: -2 } },
        { id: 'contest',      label: 'Contest with data + legal (₹0.3Cr)', cost: 0.3, description: 'Fight it with clinical data. Takes 60 days. Brand under scrutiny.', metricEffect: { equityMod: 3, awareMod: -2 } },
        { id: 'silent',       label: 'Quietly update, no communication', cost: 0,   description: 'Low cost but if media picks it up, damage is severe.', metricEffect: { equityMod: -7, awareMod: -3 } },
      ],
    },
    {
      id: 'festival-season',
      year: 2,
      category: 'Opportunity',
      categoryColour: '#10b981',
      icon: '🪔',
      title: 'Diwali Season Opportunity',
      description: 'It\'s October. India\'s biggest gifting and buying season is here. PC category typically sees 25–40% volume uplift. Retailers are ready. The question is: how big do you play?',
      impact: 'The window lasts 45 days. What you invest, you multiply.',
      options: [
        { id: 'big-play',    label: 'Full investment (₹2Cr ATL+BTL)',  cost: 2,   description: 'National TVC, in-store promos, sampling, gift packs. Maximum impact.', metricEffect: { awareMod: 8, shareMod: 1.2, trialMod: 5 } },
        { id: 'moderate',    label: 'Moderate play (₹0.8Cr)',          cost: 0.8, description: 'Digital + in-store. Good ROI without over-exposing.',  metricEffect: { awareMod: 4, shareMod: 0.5, trialMod: 2 } },
        { id: 'skip',        label: 'Skip — save for Q4 launches',     cost: 0,   description: 'Preserve budget for a Q4 new SKU launch instead.', metricEffect: {} },
      ],
    },
    {
      id: 'ambassador-crisis',
      year: 2,
      category: 'Brand Crisis',
      categoryColour: '#f43f5e',
      icon: '🔥',
      title: 'Brand Ambassador Controversy',
      description: 'Your lead celebrity endorser has been embroiled in a financial fraud controversy. It\'s trending on Twitter. Two media outlets have tied your brand to the story.',
      impact: 'Brand esteem score is dropping in real time. Media calls coming in.',
      options: [
        { id: 'drop-ambassador', label: 'Drop endorser immediately + crisis PR (₹0.5Cr)', cost: 0.5, description: 'Decisive. Temporarily bruising but protects long-term equity.', metricEffect: { equityMod: -4, awareMod: -3 } },
        { id: 'stand-by',       label: 'Stand by until verdict (loyalty)',               cost: 0.2, description: 'Demonstrates brand loyalty. High risk if allegations proven true.', metricEffect: { equityMod: -8, awareMod: -5 } },
        { id: 'silent-rebrand', label: 'Go silent on endorsement, pivot to cause',       cost: 0.4, description: 'Phase out without public drama. Use budget for a cause campaign.', metricEffect: { equityMod: 2, awareMod: -1 } },
      ],
    },
    {
      id: 'naturals-trend',
      year: 2,
      category: 'Trend',
      categoryColour: '#10b981',
      icon: '🌿',
      title: 'Clean Beauty Trend Explosion',
      description: 'Social media has turbocharged demand for "toxin-free", "sulphate-free" and "plant-based" products. Category searches for natural hair care up 180% in 3 months. Shelf space battle is on.',
      impact: 'Brands with natural credentials see 15–20% awareness bump. Others lose relevance with Gen Z.',
      options: [
        { id: 'launch-variant',  label: 'Launch a natural variant (₹1.2Cr, 6 months)', cost: 1.2, description: 'Dedicated naturals SKU. Credible. Takes time.', metricEffect: { equityMod: 8, awareMod: 5, trialMod: 4 } },
        { id: 'reposition-msgs', label: 'Reposition messaging around existing naturals', cost: 0.3, description: 'Highlight existing natural ingredients already in formula. Low cost, moderate impact.', metricEffect: { equityMod: 4, awareMod: 3 } },
        { id: 'ignore-trend',    label: 'Ignore — focus on core mass audience',         cost: 0,   description: 'Protect your existing base. Lose relevance with Gen Z / Millennials.', metricEffect: { equityMod: -3 } },
      ],
    },
    {
      id: 'retailer-demand',
      year: 3,
      category: 'Channel',
      categoryColour: '#22d3ee',
      icon: '🤝',
      title: 'Key Retailer Demands Better Terms',
      description: 'Your largest Modern Trade partner (18% of volume) is renewing contracts. They\'re demanding 5% additional margin, referencing increased shelf real estate they\'re providing.',
      impact: 'Reject and risk delisting; accept and take the margin hit.',
      options: [
        { id: 'accept-terms', label: 'Accept their terms',             cost: 0,   description: 'Margin drops 5% on MT volume. Relationship preserved. Long-term safe.', metricEffect: { gmMod: -0.03 } },
        { id: 'negotiate',    label: 'Negotiate to 3% + better shelf', cost: 0,   description: 'Middle ground. Slight margin impact but gain premium shelf placement.', metricEffect: { gmMod: -0.015, distMod: 3, trialMod: 2 } },
        { id: 'delist',       label: 'Delist from this chain',         cost: 0,   description: 'Full margin protection, but lose ~12% of volume. Redirect to GT + eComm.', metricEffect: { shareMod: -1.2, distMod: -8 } },
      ],
    },
    {
      id: 'd2c-challenger',
      year: 3,
      category: 'Competitive',
      categoryColour: '#f43f5e',
      icon: '💻',
      title: 'New Funded D2C Brand Enters',
      description: 'A new start-up just raised ₹150Cr and launched head-on in your segment with better digital presence, a sustainability angle, and a 20% lower price. TechCrunch, Forbes India covering them.',
      impact: 'They\'re growing 200% MoM on Nykaa and eating into your premium segment.',
      options: [
        { id: 'accelerate-d2c',  label: 'Accelerate your D2C + community (₹1Cr)',  cost: 1,   description: 'Build your own digital moat. First-party data, loyal base.', metricEffect: { distMod: 4, equityMod: 5, awareMod: 3 } },
        { id: 'defend-channels', label: 'Double down on offline channels',          cost: 0.5, description: 'Strengthen kirana and MT where D2C can\'t reach. Protect existing base.', metricEffect: { distMod: 6, shareMod: 0.4 } },
        { id: 'acquire',         label: 'Explore acquisition talks',               cost: 0.2, description: 'Bold move. Feasibility depends on budget and synergy assessment.', metricEffect: { equityMod: 10, awareMod: 6 } },
      ],
    },
  ],

    // ── 10 NEW EVENTS ─────────────────────────────────────────
    {
      id: 'social-scare',
      year: 1,
      category: 'Brand Crisis',
      categoryColour: '#f43f5e',
      icon: '😱',
      title: 'Viral Post Claims Allergic Reaction',
      description: 'A Twitter thread with 2.3M impressions claims your product caused a severe allergic reaction. Two major health bloggers have amplified it. A journalist has emailed requesting your official comment.',
      impact: 'Brand esteem is dropping in real-time. You have roughly a 6-hour window to shape the narrative.',
      options: [
        { id: 'respond-fast',  label: 'Respond immediately — empathy + investigation (₹0.3Cr)', cost: 0.3, description: 'Acknowledge the concern, pause the specific claim, launch internal QA investigation. Transparent and swift.', metricEffect: { equityMod: 2, awareMod: -2 } },
        { id: 'legal-hold',   label: 'All comms on legal hold — no statement yet',              cost: 0,   description: 'Legally safer short-term but dangerous for brand. Silence in a crisis is interpreted as guilt.', metricEffect: { equityMod: -8, awareMod: -4 } },
        { id: 'pr-offensive', label: 'Push back proactively with product safety data (₹0.3Cr)', cost: 0.3, description: 'Issue safety certifications and test data publicly. Works if data is solid. Risks looking defensive if data is weak.', metricEffect: { equityMod: -3, awareMod: 3 } },
      ],
    },
    {
      id: 'ipl-moment',
      year: 1,
      category: 'Opportunity',
      categoryColour: '#10b981',
      icon: '🏏',
      title: 'IPL Season Brand Integration Opportunity',
      description: 'A mid-tier IPL team has offered your brand a 10-match jersey patch deal for ₹1.5Cr — reaching 180M viewers over 45 days. Your competitor MassGlow passed on it. The slot is yours if you want it.',
      impact: 'Massive awareness potential but broad audience. IPL reaches every segment simultaneously. Does it fit your specific target?',
      options: [
        { id: 'take-deal',    label: 'Take the jersey patch deal (₹1.5Cr)',        cost: 1.5, description: 'Maximum mass reach. Best ROI for value/mass brands. Mixed strategic fit for niche premium brands.', metricEffect: { awareMod: 14, trialMod: 3 } },
        { id: 'digital-ipl', label: 'Digital-only IPL activation (₹0.5Cr)',        cost: 0.5, description: 'Leverage IPL social conversations without the jersey cost. Lower reach but precise targeting and full measurability.', metricEffect: { awareMod: 6, equityMod: 3 } },
        { id: 'pass',         label: 'Pass — not aligned with brand positioning',   cost: 0,   description: 'Protect brand positioning integrity. Right for niche premium brands. Zero short-term uplift.', metricEffect: { equityMod: 1 } },
      ],
    },
    {
      id: 'ecomm-algo',
      year: 2,
      category: 'Channel Shift',
      categoryColour: '#22d3ee',
      icon: '🔄',
      title: 'E-Commerce Algorithm Deprioritises You',
      description: 'Amazon India and Nykaa have updated ranking algorithms to favour review volume, rating count, and sponsored placement budgets. Brands with under 500 reviews are now buried on page 3+.',
      impact: 'Your e-com organic visibility has dropped 40%. Revenue from this channel fell sharply last quarter.',
      options: [
        { id: 'invest-ecomm', label: 'Invest in full e-com optimisation (₹0.8Cr)',             cost: 0.8, description: 'Sponsored listings, review generation program, A+ content upgrade. Defend the channel revenue.', metricEffect: { distMod: 6, awareMod: 4, trialMod: 3 } },
        { id: 'shift-d2c',   label: 'Accelerate D2C to reduce marketplace dependency',         cost: 0.6, description: 'Build owned direct channel. Long-term full-margin protection. Slower volume ramp.', metricEffect: { equityMod: 5, distMod: 2 } },
        { id: 'accept-drop', label: 'Accept the e-com drop, redirect budget to offline',        cost: 0,   description: 'Redirect saved budget to GT and MT channels. Absorb the e-commerce revenue decline.', metricEffect: { distMod: 3, shareMod: -0.4 } },
      ],
    },
    {
      id: 'copycat-launch',
      year: 2,
      category: 'Competitive',
      categoryColour: '#f43f5e',
      icon: '👥',
      title: 'Knockoff Brand at 30% Lower Price',
      description: 'A regional manufacturer launched a near-identical product — same positioning, similar packaging colours, nearly the same name — at 30% lower price. Kirana stores are actively substituting it at point-of-sale.',
      impact: 'Early data shows 8% trade-level substitution in 4 key markets. Growing fast with no signs of slowing.',
      options: [
        { id: 'legal-action',  label: 'Legal action + trade awareness campaign (₹0.4Cr)',       cost: 0.4, description: 'Cease & desist filing + brief all trade partners on the knockoff. Protect your shelf integrity.', metricEffect: { equityMod: 3, distMod: 2 } },
        { id: 'differentiate', label: 'Fast-track pack redesign + one key innovation (₹1Cr)',   cost: 1,   description: 'Make visual differentiation undeniable. Accelerate a new ingredient or format advantage quickly.', metricEffect: { equityMod: 8, awareMod: 4, trialMod: 3 } },
        { id: 'price-defend',  label: 'Temporary trade price discount to defend shelf',          cost: 0.5, description: 'Fight at the shelf level. Margin hit but volume protected short-term.', metricEffect: { shareMod: 0.6, gmMod: -0.04 } },
      ],
    },
    {
      id: 'tv-feature',
      year: 2,
      category: 'Opportunity',
      categoryColour: '#10b981',
      icon: '📺',
      title: 'Top Streaming Show Features Your Product',
      description: 'Your product appears organically in a popular Netflix India series — the lead character uses it prominently in 3 scenes. The episode aired last week and "#YourBrandName" is now trending on Twitter.',
      impact: '24M viewers saw the product in-context. 180K social mentions in 48 hours. A once-in-a-brand moment.',
      options: [
        { id: 'amplify',         label: 'Amplify immediately — paid social + PR (₹0.6Cr)',     cost: 0.6, description: 'Leverage the moment with paid boost, influencer outreach, and a hero social post. Maximise the wave.', metricEffect: { awareMod: 11, equityMod: 6, trialMod: 4 } },
        { id: 'organic-only',   label: 'Ride it organically — engage without any paid spend',   cost: 0,   description: 'Be present, witty, and grateful on social. Cost-free but the organic wave lasts only 48–72 hours.', metricEffect: { awareMod: 6, equityMod: 3 } },
        { id: 'placement-deal', label: 'Negotiate a formal deal for next season (₹0.4Cr)',      cost: 0.4, description: 'Turn the organic moment into a sustained brand story for Season 2. Forward-looking equity play.', metricEffect: { equityMod: 8, awareMod: 5 } },
      ],
    },
    {
      id: 'supply-disruption',
      year: 2,
      category: 'Supply Chain',
      categoryColour: '#f59e0b',
      icon: '🏭',
      title: 'Key Ingredient Supplier Goes Dark',
      description: 'Your primary supplier for a hero active ingredient — used in 3 core SKUs — has halted production due to a factory fire. Finding an alternative takes 8–12 weeks. You have 6 weeks of existing inventory.',
      impact: 'Hero SKU stockout is a real risk within 6 weeks. Distribution continuity is under serious threat.',
      options: [
        { id: 'emergency-source', label: 'Emergency alternate sourcing at premium (₹0.8Cr)', cost: 0.8, description: 'Pay 40% premium to a secondary supplier. Secured within 10 days. GM hit but supply continuity maintained.', metricEffect: { gmMod: -0.06 } },
        { id: 'ration-stock',    label: 'Ration stock — prioritise key accounts only',       cost: 0.2, description: 'Protect top 20% of accounts. Accept stockouts in secondary markets for 6–8 weeks.', metricEffect: { distMod: -5, shareMod: -0.6, equityMod: -3 } },
        { id: 'reformulate-fast', label: 'Emergency reformulation with available ingredients', cost: 0.3, description: 'Swap the ingredient quickly to maintain supply. Risks product quality perception or claims issue.', metricEffect: { equityMod: -4, distMod: 1, gmMod: -0.02 } },
      ],
    },
    {
      id: 'd2c-commission-hike',
      year: 3,
      category: 'Channel',
      categoryColour: '#22d3ee',
      icon: '💸',
      title: 'Nykaa Raises Seller Commission 6%',
      description: 'Nykaa has updated its seller agreement: commissions increase from 32% to 38% effective next month, citing "premium curation costs." Your Nykaa channel represents approximately 12% of total revenue.',
      impact: 'Your effective contribution margin on Nykaa revenue drops from ~33% to ~27%. Meaningful P&L impact at scale.',
      options: [
        { id: 'accept-hike',   label: 'Accept the new terms and stay on Nykaa',                cost: 0,   description: 'Margin drops but channel visibility and brand presence are maintained. Revenue protection prioritised over margin.', metricEffect: { gmMod: -0.04 } },
        { id: 'negotiate',     label: 'Negotiate — offer exclusive SKU for a better rate',      cost: 0.2, description: 'An exclusive Nykaa SKU gives them category differentiation; you negotiate a lower commission in return.', metricEffect: { gmMod: -0.02, equityMod: 3, distMod: 1 } },
        { id: 'reduce-nykaa', label: 'Reduce Nykaa SKUs, invest in own D2C (₹0.5Cr)',          cost: 0.5, description: 'Accept reduced Nykaa presence, invest in own website + CRM to recapture volume at full margin.', metricEffect: { equityMod: 5, distMod: -2, gmMod: 0.02 } },
      ],
    },
    {
      id: 'labelling-law',
      year: 3,
      category: 'Regulatory',
      categoryColour: '#f59e0b',
      icon: '📋',
      title: 'New Ingredient Disclosure Regulation',
      description: 'FSSAI has mandated all Personal Care products must display the top 10 ingredients by percentage on packaging within 90 days. Your formula has sulphates at 18% — higher than the category average of 11%.',
      impact: 'Disclosure is mandatory. The question is how you respond — and whether you can turn a compliance cost into a brand asset.',
      options: [
        { id: 'comply-proudly',     label: 'Comply fully — reposition around radical transparency',   cost: 0.6, description: 'Turn disclosure into a brand differentiator: "We show you everything. Always." Authenticity-led brand play.', metricEffect: { equityMod: 10, awareMod: 4 } },
        { id: 'comply-quietly',     label: 'Comply minimally — smallest font, back panel only',        cost: 0.3, description: 'Meet the legal requirement with minimum disruption. No opportunity created, but no risk either.', metricEffect: { equityMod: -1 } },
        { id: 'reformulate-comply', label: 'Reformulate to reduce sulphate + comply fully (₹1Cr)',     cost: 1,   description: 'Fix the formula AND be fully transparent about the improvement. Highest equity upside. Requires 4-month delay.', metricEffect: { equityMod: 14, awareMod: 5, trialMod: 4, gmMod: -0.03 } },
      ],
    },
    {
      id: 'global-brand-entry',
      year: 3,
      category: 'Competitive',
      categoryColour: '#f43f5e',
      icon: '🌍',
      title: 'Global Giant Enters Your Exact Segment',
      description: 'Unilever has announced the India launch of their new global naturals brand — targeting your exact segment at your price point with a ₹500Cr launch budget. Forbes India: "the challenger that ends challengers."',
      impact: 'Your segment is about to face a brand with global R&D, deep distribution, and an essentially unlimited budget.',
      options: [
        { id: 'double-equity', label: 'Double down on brand equity + community (₹1.5Cr)', cost: 1.5, description: 'Deepen your niche. Consumer community loyalty and brand equity are moats they simply cannot buy. Be irreplaceable.', metricEffect: { equityMod: 12, awareMod: 5 } },
        { id: 'niche-down',   label: 'Niche down — own one sub-segment completely',      cost: 0.5, description: 'Stop competing broadly. Become the undisputed best for one specific need (e.g., scalp health, Gen Z clean beauty).', metricEffect: { equityMod: 7, shareMod: 0.3, awareMod: 2 } },
        { id: 'price-fight',  label: 'Aggressive pricing to defend volume share',         cost: 0.3, description: 'Match or undercut the new entrant on price. Protects short-term share but dangerous for long-term brand equity.', metricEffect: { shareMod: 0.5, gmMod: -0.07, equityMod: -5 } },
      ],
    },
    {
      id: 'surprise-segment',
      year: 3,
      category: 'Market Intelligence',
      categoryColour: '#10b981',
      icon: '🔍',
      title: 'Unexpected Segment Is Loving Your Product',
      description: 'Your D2C analytics reveal a surprise: Traditional Loyalists (35–55, Tier 2 cities) are buying your premium product at 3× the rate of your target Gen Z segment. Their NPS is 72 — dramatically higher than your core segment.',
      impact: 'A larger, stickier, and more loyal segment has self-selected into your brand. Chase it or stay focused?',
      options: [
        { id: 'pivot-segment', label: 'Pivot — build a dedicated play for this new segment (₹1Cr)', cost: 1,   description: 'Create dedicated content, channel strategy, and a potential sub-SKU specifically for Traditional Loyalists.', metricEffect: { awareMod: 8, trialMod: 5, equityMod: 4, shareMod: 0.8 } },
        { id: 'dual-track',   label: 'Serve both segments simultaneously (₹0.8Cr)',                  cost: 0.8, description: 'Run parallel campaigns for Gen Z and Traditional Loyalists. Risk: diluting brand focus and losing positioning clarity.', metricEffect: { awareMod: 5, trialMod: 3, equityMod: -2, shareMod: 0.5 } },
        { id: 'stay-course',  label: 'Stay focused — Gen Z was the original strategic bet',            cost: 0,   description: 'Avoid diluting brand positioning. Trust the original targeting thesis. Traditional Loyalist adoption may be transient.', metricEffect: { equityMod: 3 } },
      ],
    },
  ],

  // ── LEARN HUB — TOPICS ──────────────────────────────────
  learnTopics: [
    {
      id: 'brand-equity',
      title: 'Brand Equity: The CBBE Framework',
      icon: '🏆',
      duration: '12 min read',
      tag: 'Foundation',
      tagColour: 'indigo',
      summary: 'Understand Keller\'s Customer-Based Brand Equity model — from Salience to Resonance. Why brand equity is the only sustainable competitive advantage in FMCG.',
      keyPoints: [
        'Brand equity = the premium consumers pay, and why they stay loyal',
        'The 4 levels of CBBE: Salience → Performance + Imagery → Judgements + Feelings → Resonance',
        'How to measure brand equity with tracking surveys',
        'Why Fair & Lovely losing equity forced a complete rename',
      ],
    },
    {
      id: 'price-pack-arch',
      title: 'Price-Pack Architecture in FMCG',
      icon: '📦',
      duration: '10 min read',
      tag: 'Strategy',
      tagColour: 'cyan',
      summary: 'How the best FMCG brands design their portfolio across price points and pack sizes to maximise penetration, margin, and loyalty simultaneously.',
      keyPoints: [
        'The sachet economy: reaching 600M consumers at ₹2–₹5/unit',
        'Hero SKU vs. flanker brand strategy',
        'Premiumisation ladder: how Dove moved consumers up the value chain',
        'How to avoid portfolio cannibalization',
      ],
    },
    {
      id: 'distribution-101',
      title: 'Distribution from Zero: The Feet-on-Street Model',
      icon: '🗺️',
      duration: '15 min read',
      tag: 'Operations',
      tagColour: 'emerald',
      summary: 'India has 12M+ retail outlets. Getting your product there — before your competitor — is half the battle. Learn how to build distribution from scratch.',
      keyPoints: [
        'Super-Stockist → Distributor → Retailer: how the chain works',
        'RSM, ASM, SR hierarchy and beat planning',
        'Numeric vs. Weighted distribution: which metric to track',
        'How Patanjali disrupted HUL by using yoga centres as distribution hubs',
      ],
    },
    {
      id: 'marketing-mix',
      title: 'Marketing Mix Modelling for FMCG',
      icon: '📊',
      duration: '13 min read',
      tag: 'Analytics',
      tagColour: 'amber',
      summary: 'How leading FMCG brands use regression-based models to determine the ROI of every rupee spent on TV, digital, trade, and PR.',
      keyPoints: [
        'Base sales vs. incremental sales: separating brand from promotion effects',
        'Media elasticity: TV drives mass awareness; digital drives targeted conversion',
        'The 60:40 rule (long-term brand vs. short-term activation)',
        'How to avoid over-investing in promotions that erode brand equity',
      ],
    },
    {
      id: 'channel-strategy',
      title: 'Omni-Channel Strategy: Playing All Fields',
      icon: '🔀',
      duration: '11 min read',
      tag: 'Strategy',
      tagColour: 'cyan',
      summary: 'Modern FMCG brands must operate in MT, GT, eCommerce, and quick commerce simultaneously — without channel conflict. Learn how.',
      keyPoints: [
        'Channel conflict: why selling on Amazon can hurt your Kirana distributor',
        'The format-product architecture: which SKUs go where',
        'D2C: the economics, the reality, and the right time to invest',
        'How Mamaearth cracked the MT shelf after 4 years of pure D2C',
      ],
    },
    {
      id: 'crisis-management',
      title: 'Brand Crisis Management',
      icon: '🚨',
      duration: '10 min read',
      tag: 'Crisis',
      tagColour: 'rose',
      summary: 'Every major FMCG brand has faced a crisis. The ones that come back do so because they acted decisively, communicated honestly, and rebuilt from consumer trust.',
      keyPoints: [
        'The 4 phases of a brand crisis: Discovery → Escalation → Resolution → Rebuilding',
        'Maggi\'s comeback: ₹450Cr investment and 9 months back to #1',
        'J&J Tylenol (1982): the gold standard for crisis response',
        'Social media: how a 48-hour window determines 2-year brand damage',
      ],
    },
  ],

  // ── LEARN HUB — MISHAP VAULT ────────────────────────────
  caseStudies: [
    {
      id: 'maggi-crisis',
      brand: 'Maggi (Nestlé India)',
      icon: '🍜',
      year: '2015',
      category: 'Product Recall / Regulatory',
      tagColour: 'rose',
      headline: 'From ₹2,600Cr to Zero in 3 Months',
      summary: 'FSSAI found lead and MSG beyond permissible limits in Maggi noodles. Nestlé pulled 38,000 tonnes from shelves. Brand value evaporated overnight.',
      whatWentWrong: 'Nestlé India initially contested the findings publicly, creating a confrontational narrative that backfired. The 2-month delay in recall cost consumer trust far more than the recall itself.',
      whatWorked: 'The comeback campaign — "We missed you too" — was one of FMCG\'s most masterful re-entries. ₹450Cr spent on quality reassurance, limited re-launch in Goa, and full transparency.',
      keyLesson: 'In a product safety crisis, speed of acknowledgement and consumer-centricity matter more than legal correctness. A 6-week contested denial caused 9 months of damage.',
      metrics: { salesBefore: '₹2,600 Crore/year', salesAfter: 'Zero (June–Nov 2015)', recovery: 'Back to #1 by Q2 2016' },
      tags: ['Recall', 'Regulatory', 'Comeback'],
    },
    {
      id: 'patanjali-disruption',
      brand: 'Patanjali (Baba Ramdev)',
      icon: '🌿',
      year: '2013–2018',
      category: 'Market Disruption / Challenger Brand',
      tagColour: 'emerald',
      headline: 'How a Yoga Guru Built a ₹9,000Cr FMCG Empire in 5 Years',
      summary: 'Patanjali disrupted HUL, P&G, Colgate and Dabur simultaneously using Ramdev\'s built-in trust, ayurvedic claims, and a price 20–30% below MNCs.',
      whatWentWrong: 'Patanjali overextended into 500+ SKUs without adequate quality control. Multiple products faced FSSAI scrutiny. The brand equity "halo" from Ramdev began to dilute with quality inconsistency.',
      whatWorked: 'Distribution through Patanjali stores, yoga centres and pharmacies — completely bypassing Kirana and MT competitors. Authenticity and national pride positioning was unbeatable at that time.',
      keyLesson: 'A challenger brand can win big by weaponising what the market leader can\'t copy — cultural authenticity, non-traditional distribution, and a passionate brand evangelist.',
      metrics: { salesBefore: '₹450Cr (FY13)', salesAfter: '₹9,000Cr+ (FY18)', recovery: 'Declined to ~₹6,000Cr post over-extension' },
      tags: ['Challenger', 'Distribution', 'Purpose Brand'],
    },
    {
      id: 'fair-lovely-rebrand',
      brand: 'Fair & Lovely → Glow & Lovely (HUL)',
      icon: '✨',
      year: '2020',
      category: 'Purpose-Led Rebrand',
      tagColour: 'indigo',
      headline: 'The Rebrand That Took 40 Years to Happen',
      summary: 'After decades of "fairness" claims that reinforced colourism, HUL finally renamed and repositioned Fair & Lovely as Glow & Lovely — removing "Fair" and "Whitening" from all claims.',
      whatWentWrong: 'The rebrand happened reactively to #BlackLivesMatter global pressure, not proactively. Consumers and activists saw it as performative. Sales actually declined short-term as brand confusion crept in.',
      whatWorked: 'Scholarship programs for women, new brand TVC featuring achievement rather than fairness — slowly rebuilt brand purpose narrative. Product quality and distribution remained strong.',
      keyLesson: 'Purpose-led rebranding only works when the internal culture changes first. Reactive purpose is seen through. And changing a brand name doesn\'t change consumer perception overnight.',
      metrics: { salesBefore: '₹3,100Cr (FY20)', salesAfter: '₹2,800Cr (FY21)', recovery: 'Gradual equity rebuild by FY23' },
      tags: ['Rebrand', 'Purpose', 'Social Pressure'],
    },
    {
      id: 'mamaearth-journey',
      brand: 'Mamaearth',
      icon: '🌱',
      year: '2016–2023',
      category: 'D2C to Omni-Channel Scaling',
      tagColour: 'emerald',
      headline: 'WhatsApp Orders to ₹1,500Cr Brand in 7 Years',
      summary: 'Started as a toxin-free baby care brand sold on WhatsApp and Amazon. Scaled to a ₹1,500Cr+ brand now available in DMart, Reliance, and 1 lakh kirana stores.',
      whatWentWrong: 'MT expansion required compromising on premium positioning (price discounting). Short-term marketing ROI chasing led to over-reliance on performance marketing vs. brand building, hurting equity.',
      whatWorked: 'Building a category before a product — Mamaearth created the "toxin-free" conversation. Strong Instagram community before product launch. Celebrity co-creation (Shilpa Shetty).',
      keyLesson: 'D2C is a brand-building tool, not just a sales channel. Moving to offline is inevitable for scale — but requires rebuilding your brand positioning for a broader, less-educated audience.',
      metrics: { salesBefore: '₹1Cr (FY17)', salesAfter: '₹1,500Cr+ (FY23)', recovery: 'Successfully IPO-listed (Honasa Consumer)' },
      tags: ['D2C', 'Scaling', 'Brand Building'],
    },
    {
      id: 'bingo-vs-lays',
      brand: 'Bingo! (ITC) vs. Lays (PepsiCo)',
      icon: '🥨',
      year: '2007–2012',
      category: 'Price War / Challenger Strategy',
      tagColour: 'amber',
      headline: 'How ITC Took 25% Market Share from Frito-Lay in 3 Years',
      summary: 'ITC leveraged its massive kirana distribution, quirky local advertising, and Indian-taste innovations to build Bingo! as a genuine challenger to Lays — without a price war.',
      whatWentWrong: 'ITC briefly over-extended to too many local flavours, causing supply chain issues. Some SKUs failed quality consistency tests in Year 2.',
      whatWorked: 'ITC\'s backbone: 6.5M retail touchpoints. They didn\'t fight Lays on advertising — they out-distributed them in Tier 2–4 cities where Lays was thin. Pricing parity with differentiated flavours (Mad Angles, Tedhe Medhe) created real differentiation.',
      keyLesson: 'Don\'t fight a market leader\'s strength (advertising money). Attack their distribution weakness. A challenger brand with 30% of the ad budget can win 25% share with superior GT distribution.',
      metrics: { salesBefore: 'Zero (pre-2007)', salesAfter: '₹2,000Cr+ (2012)', recovery: 'Sustained #2 position' },
      tags: ['Price War', 'Distribution', 'Challenger'],
    },
    {
      id: 'dove-real-beauty',
      brand: 'Dove (Unilever)',
      icon: '🕊️',
      year: '2004–Present',
      category: 'Purpose-Led Branding / Controversy',
      tagColour: 'cyan',
      headline: 'The Campaign That Redefined Advertising — And Its Shadow',
      summary: 'Dove\'s "Real Beauty" campaign (2004) was groundbreaking — real women, real bodies, no retouching. It drove 700% revenue growth over 10 years. But it also hit controversies along the way.',
      whatWentWrong: '2017: A Facebook ad appeared to show a Black woman "becoming" white after using Dove body wash — a catastrophic editing error. Twitter exploded. Dove pulled it and apologised within 24 hours.',
      whatWorked: 'The core idea — celebrating authentic beauty — never wavered. Response to the 2017 crisis was fast, accountable, and human. The brand\'s equity was strong enough to survive.',
      keyLesson: 'A brand with strong purpose equity can recover from executional errors faster than one that doesn\'t have it. But purpose brands are held to a higher standard — even honest mistakes feel like hypocrisy.',
      metrics: { salesBefore: '$2B (2004)', salesAfter: '$5.1B (2014)', recovery: 'Brand equity remained top-3 global PC brand' },
      tags: ['Purpose', 'Crisis Recovery', 'Global Brand'],
    },
  ],

};
